[profile.default]
libs = ["lib"]
out = "out"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@uniswap/v3-periphery=lib/v3-periphery",
  "@uniswap/v3-core=lib/v3-core",
]
src = "src"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "./"}]